---
- name: creating user
  hosts: all
  become: true
  tasks:
  - name: creating user john  
    user: 
      name: sonia

  - name: create a directory
    file:
      path: /opt/sonia_temp_dir
      state: directory
      owner: sonia
      group: sonia
      mode: 0755    


